src/Abp.EmailMarketing.Web/Pages/Contacts/CreateModal.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Abp.EmailMarketing.Contacts;
using Abp.EmailMarketing.Web.Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Form;

namespace Abp.EmailMarketing.Web.Pages.Contacts
{
    public class CreateModalModel : EmailMarketingPageModel
    {
        [BindProperty]
        public CreateContactViewModel Contact { get; set; }

        [BindProperty]
        public List<SelectListItem> Groups { get; set; }

        [BindProperty]
        public List<string> Result { get; set; }

        private readonly IContactAppService _contactAppService;

        public CreateModalModel(IContactAppService contactAppService, IContactRepository contactRepository)
        {
            _contactAppService = contactAppService;
        }

        public async Task OnGetAsync()
        {
            Contact = new CreateContactViewModel();

            var groupLookup = await _contactAppService.GetGroupLookupAsync();
            Groups = groupLookup.Items.Select(x => new SelectListItem(x.Name, x.Id.ToString())).ToList();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            List<Guid> groupid = new List<Guid>();
            for (int i = 0; i < Result.Count; i++)
            {
                groupid.Add(Guid.Parse(Result[i]));
            }

            Contact.GroupIds = groupid;
            
            await _contactAppService.CreateAsync(
                ObjectMapper.Map<CreateContactViewModel, CreateUpdateContactDto>(Contact)    
            );
            return NoContent();
        }

        public class CreateContactViewModel
        {
            public List<Guid> GroupIds { get; set; }

            [Required]
            [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Email is not valid")]
            public string Email { get; set; }

            [Required]
            [StringLength(64)]
            public string FirstName { get; set; }

            [Required]
            [StringLength(64)]
            public string LastName { get; set; }

            [Required]
            [DataType(DataType.Date)]
            public DateTime DateOfBirth { get; set; } = DateTime.Now;

            [DataType(DataType.PhoneNumber)]
            [StringLength(15, MinimumLength = 10, ErrorMessage = "The phone number's length must be between 10 and 15")]
            public string PhoneNumber { get; set; }

            [TextArea]
            public string Addition { get; set; }

            public int Status { get; set; }
        }
    }
}

src/Abp.EmailMarketing.Web/Pages/Contacts/ImportContact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Abp.EmailMarketing.Contacts;
using Abp.EmailMarketing.GroupContacts;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Abp.EmailMarketing.Web.Pages.Contacts
{
    public class ImportContactModel : EmailMarketingPageModel
    {
        private readonly IContactAppService _contactAppService;
        private readonly IGroupRepository _groupRepository;


        public ImportContactModel(IContactAppService contactAppService, IGroupRepository groupRepository)
        {
            _contactAppService = contactAppService;
            _groupRepository = groupRepository;
        }

        public void OnGet()
        {
        }

        public List<ContactDto> ContactDtos = new List<ContactDto>();

        public async Task<IActionResult> OnPostImportAsync()
        {
            List<CreateUpdateContactDto> createUpdateContactDtos = new List<CreateUpdateContactDto>();
            IFormFile excel = Request.Form.Files[0];
            if (excel == null)
            {
                return NoContent();
            }

            using (var workbook = new XLWorkbook(excel.OpenReadStream()))
            {
                var worksheet = workbook.Worksheet("Contact");

                var count = 0;
                foreach (var row in worksheet.Rows())
                {
                    count += 1;
                    if (count > 1) //skip the first row.
                    {
                        if (row.Cell(1).Value.Equals("") || row.Cell(2).Equals("") || row.Cell(3).Equals("")
                            || row.Cell(4).Equals("") || row.Cell(5).Equals(6)) break;
                        ContactDtos.Add(
                            new ContactDto()
                            {
                                //GroupName = row.Cell(1).Value.ToString(),
                                Email = row.Cell(2).Value.ToString(),
                                FirstName = row.Cell(3).Value.ToString(),
                                LastName = row.Cell(4).Value.ToString(),
                                DateOfBirth = row.Cell(5).Value.To<DateTime>(),
                                PhoneNumber = row.Cell(6).Value == null ? "" : row.Cell(6).Value.ToString(),
                                Addition = row.Cell(7).Value == null ? "" : row.Cell(7).Value.ToString(),
                                Status = row.Cell(8).Value.Equals("") ? 0 : row.Cell(8).Value.To<int>()
                            }
                        );
                        createUpdateContactDtos.Add(
                            new CreateUpdateContactDto()
                            {
                                //GroupId = _groupRepository.FindByNameAsync(row.Cell(1).Value.ToString()).Result.Id,
                                Email = row.Cell(2).Value.ToString(),
                                FirstName = row.Cell(3).Value.ToString(),
                                LastName = row.Cell(4).Value.ToString(),
                                DateOfBirth = row.Cell(5).Value.To<DateTime>(),
                                PhoneNumber = row.Cell(6).Value == null ? "" : row.Cell(6).Value.ToString(),
                                Addition = row.Cell(7).Value == null ? "" : row.Cell(7).Value.ToString(),
                                Status = row.Cell(8).Value.Equals("") ? 0 : row.Cell(8).Value.To<int>()
                            }
                        );
                    }
                }

                foreach(CreateUpdateContactDto createUpdateContactDto in createUpdateContactDtos)
                {
                    await _contactAppService.CreateAsync(createUpdateContactDto);
                }

                //View result ajax 
                StringBuilder sb = new StringBuilder();
                sb.Append("<table class='table table-bordered'><tr>");
                sb.Append("<th>Group Contact</th>");
                sb.Append("<th>Email</th>");
                sb.Append("<th>FirstName</th>");
                sb.Append("<th>LastName</th>");
                sb.Append("<th>DateOfBirth</th>");
                sb.Append("<th>PhoneNumber</th>");
                sb.Append("</tr>");
                sb.AppendLine("<tr>");
                foreach(ContactDto contactDto in ContactDtos)
                {
                    //sb.Append("<td>" + contactDto.GroupName + "</td>");
                    sb.Append("<td>" + contactDto.Email + "</td>");
                    sb.Append("<td>" + contactDto.FirstName + "</td>");
                    sb.Append("<td>" + contactDto.LastName + "</td>");
                    sb.Append("<td>" + contactDto.DateOfBirth + "</td>");
                    sb.Append("<td>" + contactDto.PhoneNumber + "</td>");
                    sb.AppendLine("</tr>");
                }
                sb.Append("</table>");

                return this.Content(sb.ToString());
            }
        }
    }
}

src/Abp.EmailMarketing.Web/Pages/Contacts/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Abp.EmailMarketing.Web.Pages.Contacts
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/Abp.EmailMarketing.Web/Pages/GroupContacts/ContactView.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Abp.EmailMarketing.Contacts;
using Abp.EmailMarketing.GroupContacts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Abp.EmailMarketing.Web.Pages.GroupContacts
{
    public class ContactViewModel : EmailMarketingPageModel
    {

        public List<ContactView> ContactDtos { get; set; }
        public List<ContactView> ContactOld { get; set; }
        [BindProperty]
        public GroupId Groupid { get; set; }
        [BindProperty]
        public List<string> ContactSave { get; set; }

        private readonly IGroupAppService _groupAppService;
        private readonly IContactAppService _contactAppService;

        public ContactViewModel(IGroupAppService groupAppService, IContactAppService contactAppService)
        {
            _groupAppService = groupAppService;
            _contactAppService = contactAppService;
        }

        public async Task OnGetAsync(Guid Id)
        {
            var contacts = await _groupAppService.GetListContact();
            ContactDtos = ObjectMapper.Map<List<ContactDto>, List<ContactView>>(contacts);
            var contactOld = await _groupAppService.GetListContactByGroup(Id);
            ContactOld = ObjectMapper.Map<List<ContactDto>, List<ContactView>>(contactOld);
            Groupid = new GroupId();
            Groupid.Id = Id;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            SaveModel save = new SaveModel();
            save.GroupId = Groupid.Id;
            var list = new List<Guid>();
            for (int i = 0; i < ContactSave.Count; i++)
            {
                list.Add(Guid.Parse(ContactSave[i]));
            }
            save.Id = list;
            await _groupAppService.UpdateContactInGroup(
                ObjectMapper.Map<SaveModel, UpdateContactInGroupDto>(save)
            );
            return NoContent();
        }

        public class ContactView
        {
            [HiddenInput]
            public Guid Id { get; set; }
            public string Email { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
            public string DateOfBirth { get; set; }
        }
        public class GroupId
        {
            [HiddenInput]
            public Guid Id { get; set; }
        }

        public class SaveModel
        {
            public List<Guid> Id { get; set; }
            public Guid GroupId { get; set; }
        }
    }
}

src/Abp.EmailMarketing.Web/Pages/GroupContacts/ImportContact.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Abp.EmailMarketing.Contacts;
using Abp.EmailMarketing.GroupContacts;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Abp.EmailMarketing.Web.Pages.GroupContacts
{
    public class ImportContactModel : EmailMarketingPageModel
    {
        public Guid Id { get; set; }

        private readonly IContactAppService _contactAppService;
        private readonly IGroupRepository _groupRepository;

        public ImportContactModel(IContactAppService contactAppService, IGroupRepository groupRepository)
        {
            _contactAppService = contactAppService;
            _groupRepository = groupRepository;
        }

        public void OnGet(string id)
        {
            Id = Guid.Parse(id);
        }

        public async Task<IActionResult> OnPostImportAsync()
        {
            List<CreateUpdateContactDto> createUpdateContactDtos = new List<CreateUpdateContactDto>();
            IFormFile excel = Request.Form.Files[0];
            if (excel == null)
            {
                return NoContent();
            }

            StringBuilder sb = new StringBuilder();
            sb.Append("<table class='table table-bordered table-hover'><tr>");
            sb.Append("<th>Email</th>");
            sb.Append("<th>First Name</th>");
            sb.Append("<th>Last Name</th>");
            sb.Append("<th>Date of birth</th>");
            sb.Append("<th>PhoneNumber</th>");
            sb.Append("<th>Addition</th>");
            sb.Append("</tr>");


            using (var workbook = new XLWorkbook(excel.OpenReadStream()))
            {
                var worksheet = workbook.Worksheet("Contact");
                var count = 0;
                foreach (var row in worksheet.Rows())
                {
                    count += 1;
                    if (count > 1) //skip the first row.
                    {
                        if (row.Cell(1).Value.Equals("") || row.Cell(2).Value.Equals("")
                           || row.Cell(3).Value.Equals("") || row.Cell(4).Value.Equals("")) break;
                        var groupName = row.Cell(7).Value.ToString();
                        var group = await _groupRepository.FindByNameAsync(groupName);
                        var createContactDto = new CreateUpdateContactDto()
                        {
                            GroupIds = new List<Guid>() { group.Id },
                            Email = row.Cell(1).Value.ToString(),
                            FirstName = row.Cell(2).Value.ToString(),
                            LastName = row.Cell(3).Value.ToString(),
                            DateOfBirth = row.Cell(4).Value.To<DateTime>(),
                            PhoneNumber = row.Cell(5).Value == null ? "" : row.Cell(5).Value.ToString(),
                            Addition = row.Cell(6).Value == null ? "" : row.Cell(6).Value.ToString(),
                            Status = 0
                        };
                        try
                        {
                            await _contactAppService.CreateAsync(
                                createContactDto
                            );
                            sb.AppendLine("<tr>");
                            sb.Append("<td>" + createContactDto.Email + "</td>");
                            sb.Append("<td>" + createContactDto.FirstName + "</td>");
                            sb.Append("<td>" + createContactDto.LastName + "</td>");
                            sb.Append("<td>" + createContactDto.DateOfBirth + "</td>");
                            sb.Append("<td>" + createContactDto.PhoneNumber + "</td>");
                            sb.Append("<td>" + createContactDto.Addition + "</td>");
                            sb.AppendLine("</tr>");
                        }
                        catch (Exception ex)
                        {
                            sb.AppendLine($"<tr class='table-danger'>");
                            sb.Append("<td>" + createContactDto.Email + "</td>");
                            sb.Append("<td>" + createContactDto.FirstName + "</td>");
                            sb.Append("<td>" + createContactDto.LastName + "</td>");
                            sb.Append("<td>" + createContactDto.DateOfBirth + "</td>");
                            sb.Append("<td>" + createContactDto.PhoneNumber + "</td>");
                            sb.Append("<td>" + createContactDto.Addition + "</td>");
                            sb.AppendLine("</tr>");
                            Console.WriteLine(ex);
                        }
                    }
                }

                //View result ajax 
                sb.Append("</table>");

                return this.Content(sb.ToString());
            }
        }

        public async Task<IActionResult> OnPostDownloadAsync()
        {
            /*if (filename == null)
                return Content("filename not present");*/

            var path = Path.Combine(
                           Directory.GetCurrentDirectory(),
                           "wwwroot\\File", "ContactDto.xlsx");

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, GetContentType(path), Path.GetFileName(path));
        }

        private string GetContentType(string path)
        {
            var types = GetMimeTypes();
            var ext = Path.GetExtension(path).ToLowerInvariant();
            return types[ext];
        }

        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
            {
                {".txt", "text/plain"},
                {".pdf", "application/pdf"},
                {".doc", "application/vnd.ms-word"},
                {".docx", "application/vnd.ms-word"},
                {".xls", "application/vnd.ms-excel"},
                {".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
                {".png", "image/png"},
                {".jpg", "image/jpeg"},
                {".jpeg", "image/jpeg"},
                {".gif", "image/gif"},
                {".csv", "text/csv"}
            };
        }
    }
}

src/Abp.EmailMarketing.Web/Pages/GroupContacts/ContactView.cshtml
@page
@using Abp.EmailMarketing.Localization
@using Abp.EmailMarketing.Web.Pages.GroupContacts
@using Microsoft.Extensions.Localization
@using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Modal
@model ContactViewModel
@inject IStringLocalizer<EmailMarketingResource> L

@{
    Layout = null;
}

<form asp-page="/GroupContacts/ContactView">
    <abp-modal size="Large" id="ContactViewModal">
        <abp-modal-header title="@L["Contacts"]"></abp-modal-header>
        <abp-modal-body>
            <div class="overflow-auto bg-light m-1" style="height: 400px">
                <abp-input asp-for="@Model.Groupid.Id"></abp-input>
                <table class="table table-hover overflow-auto">
                    <thead>
                        <tr>
                            <th></th>
                            <th>FirstName</th>
                            <th>LastName</th>
                            <th>Email</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.ContactDtos.Count; i++)
                        {
                            <tr>
                                <td>

                                    <div class="form-check">
                                        @if (Model.ContactOld.Any(c => c.Id.ToString().Equals(@Model.ContactDtos[i].Id.ToString())))
                                        {
                                            <input class="form-check-input" type="checkbox" id="@Model.ContactDtos[i]" value="@Model.ContactDtos[i].Id" name="ContactSave" checked />
                                        }
                                        else
                                        {
                                            <input class="form-check-input" type="checkbox" id="@Model.ContactDtos[i]" value="@Model.ContactDtos[i].Id" name="ContactSave" />
                                        }
                                    </div>
                                </td>
                                <td>@Model.ContactDtos[i].FirstName</td>
                                <td>@Model.ContactDtos[i].LastName</td>
                                <td>@Model.ContactDtos[i].Email</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </abp-modal-body>
        <abp-modal-footer buttons="@(AbpModalButtons.Cancel)|(AbpModalButtons.Save)"></abp-modal-footer>
    </abp-modal>
</form>

src/Abp.EmailMarketing.Web/Pages/GroupContacts/CreateModal.cshtml
@page
@using Abp.EmailMarketing.Localization
@using Abp.EmailMarketing.Web.Pages.GroupContacts
@using Microsoft.Extensions.Localization
@using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Modal
@model CreateModalModel
@inject IStringLocalizer<EmailMarketingResource> L
@{
    Layout = null;
}
<form asp-page="/GroupContacts/CreateModal">
    <abp-modal>
        <abp-modal-header title="@L["NewGroup"].Value"></abp-modal-header>
        <abp-modal-body>
            <abp-input asp-for="Group.Name" />
            <abp-input asp-for="Group.Description" />
        </abp-modal-body>
        <abp-modal-footer buttons="@(AbpModalButtons.Cancel|AbpModalButtons.Save)"></abp-modal-footer>
    </abp-modal>
</form>

src/Abp.EmailMarketing.Web/Pages/GroupContacts/EditModal.cshtml
@page
@using Abp.EmailMarketing.Localization
@using Abp.EmailMarketing.Web.Pages.GroupContacts
@using Microsoft.Extensions.Localization
@using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Modal
@model EditModalModel
@inject IStringLocalizer<EmailMarketingResource> L
@{
    Layout = null;
}
<form asp-page="/GroupContacts/EditModal">
    <abp-modal>
        <abp-modal-header title="@L["Update"].Value"></abp-modal-header>
        <abp-modal-body>
            <abp-input asp-for="Group.Id" />
            <abp-input asp-for="Group.Name" />
            <abp-input asp-for="Group.Description" />
        </abp-modal-body>
        <abp-modal-footer buttons="@(AbpModalButtons.Cancel|AbpModalButtons.Save)"></abp-modal-footer>
    </abp-modal>
</form>

src/Abp.EmailMarketing.Web/Pages/GroupContacts/ImportContact.cshtml
@page
@using Microsoft.AspNetCore.Mvc.Localization
@using Abp.EmailMarketing.Localization
@using Volo.Abp.Users
@using Abp.EmailMarketing.Web.Pages.GroupContacts
@model ImportContactModel
@inject IHtmlLocalizer<EmailMarketingResource> L
@*@section styles {
        <abp-style-bundle>
            <abp-style src="/Pages/Index.css" />
        </abp-style-bundle>
    }*@
@section scripts {
    <abp-script src="/Pages/GroupContacts/Import.js" />
}

<abp-card>
    <abp-card-body>
        <h5>Select excel file to Import</h5>
        <div class="row">
            <div class="col-sm-6">
                <form method="POST" enctype="multipart/form-data" asp-page-handler="Import" class="form">
                    <input type="file" name="files" id="fileupload" />
                    <abp-button button-type="Primary" id="btnupload">Import contact from excel</abp-button>
                </form>
            </div>
            <div class="col-sm-6">
                <div class="col-sm-6">
                    <form method="POST" enctype="multipart/form-data" asp-page-handler="Download" class="text-right">
                        <abp-button button-type="Primary" type="submit" id="btndownload" text="Dowload exampleFile" />
                    </form>
                </div>
            </div>
        </div>
        <div class="row m-2">
            <div id="divPrint"></div>
        </div>
    </abp-card-body>
</abp-card>

src/Abp.EmailMarketing.Web/Pages/GroupContacts/Index.cshtml
@page
@using Abp.EmailMarketing.Localization
@using Abp.EmailMarketing.Permissions
@using Abp.EmailMarketing.Web.Pages.GroupContacts
@using Microsoft.AspNetCore.Authorization
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<EmailMarketingResource> L
@inject IAuthorizationService AuthorizationService
@model IndexModel

@section scripts
{
    <abp-script src="/Pages/GroupContacts/Index.js" />
    <abp-style src="/libs/myStyle/Index.css" />
}

<abp-card>
    <abp-card-header>
        <abp-row>
            <abp-column size-md="_6">
                <abp-card-title>@L["Groups"]</abp-card-title>
            </abp-column>
            <abp-column size-md="_6" class="text-right">
                @if (await AuthorizationService
                  .IsGrantedAsync(EmailMarketingPermissions.Groups.Create))
                {
                    <abp-button id="NewGroupButton"
                                text="@L["NewGroup"].Value"
                                icon="plus"
                                button-type="Primary" />
                }
            </abp-column>
        </abp-row>
    </abp-card-header>
    <abp-card-body>
        <abp-table striped-rows="true" id="GroupsTable">

        </abp-table>
    </abp-card-body>
</abp-card>